"""add states and status to conversations

Revision ID: 2bc25ccb3657
Revises: rev_010
Create Date: 2026-04-05 23:45:19.625663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bc25ccb3657'
down_revision: Union[str, None] = 'rev_010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('states', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('conversations', sa.Column('status', sa.VARCHAR(length=50), server_default='active', nullable=False))
    op.drop_index('idx_entries_audio_source', table_name='entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_entries_audio_source', 'entries', ['audio_source'], unique=False)
    op.drop_column('conversations', 'status')
    op.drop_column('conversations', 'states')
    # ### end Alembic commands ###
